version: '3.1'

services:
  odp-ui:
    image: registry.ncats.nih.gov:5000/odp-ui:current
    networks:
      - reverse-proxy
    expose:
      - 8000
    container_name: odp-ui
    restart: always
    hostname: opendata-dev.ncats.nih.gov-variant
    environment:
      ENV_CUR: DEV
      VIRTUAL_HOST: opendata-dev.ncats.nih.gov
      VIRTUAL_PORT: 8000
      SERVICE_PATH: /
      UPSTREAM: opendata-dev.ncats.nih.gov-ui
      SERVICES_AUTH_URL: https://a.labshare.org/_api
      SERVICES_AUTH_CLIENT_ID:
      SERVICES_AUTH_TENANT: ncats
    volumes:
      - ${WORKSPACE}/config/dev.json:/var/www/app/config/config.json
    logging:
      driver: splunk
      options:
        splunk-token: "d203cee5-13f9-488c-b3eb-20ff9be2c6c7"
        splunk-url: "https://splunkhf03.ncats.nih.gov:8088"
        tag: "nih_ncats_docker_opendata_ui_dev"
        splunk-insecureskipverify: "true"
        splunk-verify-connection: "false"
        splunk-format: "json"
    labels:
      - "gov.nih.ncats.appname=odp-ui"
      - "gov.nih.ncats.appenv=dev"
      - "gov.nih.ncats.appentry=opendata-dev.ncats.nih.gov/variant"
      - "gov.nih.ncats.appentrytype=https"
      - "gov.nih.ncats.appentryport=443"

networks:
  reverse-proxy:
    external:
      name: reverse-proxy